name: Docker Image push to registry

on:
  push:
    branches: [ "master" ]
    
env:
  BUILD_DIR: UOTDBot
  IMAGE_NAME: uotd-bot
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: recursive
    - name: Build Docker image
      run: |
        cd $BUILD_DIR
        docker build . -t $REGISTRY_URL/$IMAGE_NAME --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image to registry
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login $REGISTRY_URL --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker push $REGISTRY_URL/$IMAGE_NAME
        
