name: Docker Image Publish

on:
  release:
    types: [ published ]

env:
  BUILD_DIR: UOTDBot
  IMAGE_NAME: uotd-bot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set lowercase repository_owner and tag_name without v
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        echo "VERSION=${TAG#v}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'
        TAG: '${{ github.event.release.tag_name }}'
      
    - name: Build Docker Image
      run: |
        cd $BUILD_DIR
        docker build . -t ghcr.io/$OWNER_LC/$IMAGE_NAME -t ghcr.io/$OWNER_LC/$IMAGE_NAME:$VERSION
    
    - name: Push the Docker image to ghcr.io
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
        docker push ghcr.io/$OWNER_LC/$IMAGE_NAME --all-tags
    
    - name: Push the Docker image to hub.docker.com
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME --all-tags
